#!/bin/bash
branch=$1
template=`cat .github/ISSUE_TEMPLATE/deploy_homolog.md`
template="${template/\{branch\}/feature}"
body=$(echo "$template" | awk '/## Description/ {p=1} p')

gh issue create --title "Automatico" -l build-homolog -F - <<< $body