#!/bin/bash
# branch=$1
# command="s/{branch}/$branch/g .github/ISSUE_TEMPLATE/deploy_homolog.md"
# echo `sed $command`

# gh issue create --title "Teste automatizado" --body "$body"

sucesso=0
falha=1

#------

branch_exists=$falha
branch_merged=$falha

if [ $branch_exists -eq 0 ] && [ $branch_merged -ne 0 ]; then
    echo "Faz o merge"
else
    echo "Retira da lista"
fi