name: Verify deploy

on:
  pull_request:
    types: [synchronize, ready_for_review, opened, reopened, edited, labeled, unlabeled]

# on:
#   workflow_dispatch:  # Permite a ativação manual do workflow

jobs:
  check_deploy_status:
    runs-on: ubuntu-latest

    steps:
      - name: Check Deploy Status
        id: check_deploy
        run: |
          # Verifica o status do último workflow de Deploy
          STATUS=$(curl \
            --request GET \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url "https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yaml/runs" | jq -r '.workflow_runs[0].status')
          # Define uma saída para o status do workflow
          echo ${STATUS}
          echo "data=${STATUS}" >> $GITHUB_OUTPUT

      - name: Block Merge if Deploy Running
        run: |
          if [[ "${{ steps.check_deploy.outputs.data }}" == "completed" ]]; then
            echo "It works!"
            exit 0
          fi
          echo "##[error]O merge foi bloqueado porque o workflow Deploy está em execução."
          exit 1
