name: Block Merge When Deploy Running

on:
  pull_request:
    types: [synchronize, ready_for_review]

jobs:
  check_deploy_status:
    runs-on: ubuntu-latest

    steps:
      - name: Check Deploy Status
        id: check_deploy
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/actions/runs
          repository: ${{ github.repository }}
          query: |
            per_page=1
            event=pull_request
            status=in_progress
            workflow=Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Block Merge if Deploy Running
        run: |
          if [ "${{ steps.check_deploy.outputs.data }}" != "[]" ]; then
            echo "##[error]O merge foi bloqueado porque o workflow Deploy está em execução."
            exit 1
          fi
