name: Dispatcher

on:
  workflow_dispatch:  # Permite a ativação manual do workflow

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Relatorio
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh workflow run simple-workflow.yaml --ref develop

      - name: Who you gonna call?
        uses: ./.github/workflows/simple-worflow.yaml
        with:
          ref: develop
