name: Dispatcher

on:
  workflow_dispatch:  # Permite a ativação manual do workflow

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

  who-you-gonna-call:
    uses: ./.github/workflows/simple-workflow.yaml
    with:
      ref: deploy
