name: Manual

on:
  workflow_dispatch:  # Permite a ativação manual do workflow

concurrency:
  group: verify-concurrence

jobs:
  principal:
    runs-on: ubuntu-latest
    outputs:
      erro_job: ${{ steps.tarefa.outputs.mensagem_erro }}
    steps:
      - name: Passo principal
        id: tarefa
        run: |
          echo "mensagem_erro=Uma mensagem de erro" >> $GITHUB_OUTPUT
          exit 1

      # - name: Relatório final
      #   if: failure()
      #   run: |
      #     echo "Ocorreram erros!"
      #     echo "- ${{ steps.main.outputs.error }}"

      # - name: Report
      #   if: failure()
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh run view ${{ github.run_id }} --log | grep error

  relatorio:
    runs-on: ubuntu-latest
    needs: [ principal ]
    steps:
      - name: Relatório final
        if: failure()
        run: |
          echo "Ocorreram erros!"
          echo "- Por step: ${{ needs.principal.steps.tarefa.outputs.mensagem_erro }}"
          echo "- Por output: ${{ needs.principal.outputs.erro_job }}"
